spring:
  datasource:
    username: root
    password: wal14.
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource	# 主要是这一项

    # 以下为Druid连接池的配置
    initialSsize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60_000
    testWhileIdle: true
    testOnRun: false
    poolPreparedStatements: true
mybatis:
  mapper-locations: classpath:com/ermao/mapper/*.xml
  type-aliases-package: com.ermao.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl